// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Greate201911271111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Greate201911271111));
        
        string IMigrationMetadata.Id
        {
            get { return "201911270911302_Greate201911271111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
